name: Setup Environment

runs:
  using: composite
  steps:
  - name: Publish JUnit Results
    uses: dorny/test-reporter@v1
    if: always()
    with:
      name: Jest Test Results
      reporter: jest-junit
      path: test-results/junit/*.xml
      fail-on-error: false
      only-summary: true
