name: CI

on:
- push

jobs:
  build:
    name: Build TypeScript
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-env
    - name: Run TypeScript Compiler
      run: pnpm build
  lint:
    name: Check ESLint
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-env
    - name: Run ESLint
      run: pnpm --silent lint
  test:
    name: Check Jest
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      checks: write
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-env
    - name: Run Jest
      run: pnpm --silent test
    - uses: ./.github/actions/publish-test-results
      if: always()
