name: CI

on:
- push

jobs:
  build:
    name: Build TypeScript
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Environment
      uses: ./.github/actions/setup-env
    - name: Run TypeScript Compiler
      run: pnpm build
  lint:
    name: Check ESLint
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      checks: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup Environment
      uses: ./.github/actions/setup-env
    - name: Run ESLint
      run: pnpm --silent lint
    - name: Publish Results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: test-results/sarif/
  test:
    name: Check Jest
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      checks: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup Environment
      uses: ./.github/actions/setup-env
    - name: Run Jest
      run: pnpm --silent test
    - name: Publish Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: ${{ inputs.name }}
        reporter: jest-junit
        path: test-results/junit/*.xml
        fail-on-error: false
        only-summary: true
        max-annotations: 50
