name: CI

on:
- push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-env
      with:
        node-version: 18
    - name: Run TypeScript Compiler
      run: pnpm build
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-env
      with:
        node-version: 18
    - name: Run ESLint
      run: pnpm --silent lint
    # - name: Publish JUnit Results
    #   uses: mikepenz/action-junit-report@v3
    #   if: always()
    #   with:
    #     report_paths: test-results/**.junit.xml
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-env
      with:
        node-version: 18
    - name: Run Jest
      run: pnpm --silent test
