name: CI

on:
- push

jobs:
  build:
    name: Build TypeScript
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-env
    - name: Run TypeScript Compiler
      run: pnpm build
  lint:
    name: Check ESLint
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-env
    - name: Run ESLint
      run: pnpm --silent lint
  test:
    name: Check Jest
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-env
    - name: Run Jest
      run: pnpm --silent test
      continue-on-error: true
    - name: Publish JUnit Results
      uses: mikepenz/action-junit-report@v3
      with:
        report_paths: test-results/junit/*.xml
